theme: jekyll-theme-cayman

# GitHub defaults to generating README.md -> index.html on GitHub Pages
# but on Netlify needs this extra config

#remote_theme: pages-themes/cayman@v0.2.0

plugins:
  # GitHub loads front matter automatically
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  #- jekyll-remote-theme

title : CI/CD Status Page
tagline: CICI/CD Status page for Hari Sekhon's GitHub repos
author:
  name: Hari Sekhon
  email: harisekhon@gmail.com
  github: harisekhon
  twitter: harisekhon
  linkedin: harisekhon

include:
  - README.md
defaults:
  - scope:
      path: README.md
    values:
      # needed layout to get theme to apply in index.html to show on Netlify
      layout: default
      # GitHub adds this with a link to the CI-CD repo, but outside GitHub Pages must add something ourself
      #title: CI/CD Status Page
      #tagline: CI/CD Status page for Hari Sekhon's GitHub repos
      # needed to get it to generate index.html rather than README.html, so that we don't get 404 error on base site
      permalink: index.html
